version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.3
    working_directory: ~/cumulus-distribution-api
    steps:
      - checkout

      # restore cache
      - restore_cache:
          keys:
            - cumulus-distribution-api-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: Installing Dependencies
          command: npm install

      # save node_module and yarn-cache folders
      - save_cache:
          key: cumulus-distribution-api-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/cumulus-distribution-api/node_modules


      - add_ssh_keys:
          fingerprints:
            - "9c:ca:23:5a:80:73:65:6b:1a:71:8e:d5:85:dd:a2:a7"

      - deploy:
          name: deploy documentation to gh-pages
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run build
              npm run deploy
            fi
